### ISSUE TITLE
metapasata: proposal vs reality

### ISSUE THREAD

**Issue by evdokim** [ohnosequences/IWBBIO-2014#5]
The proposal has more features that have been implemented now:
- BIOM output format
- Lowest Common ancestor Paradigm for assignment

should I tried to implement it? or just keep silence.

**Comment by laughedelic** [comment]
_metapasata_ :ok_hand:

**Comment by marina-manrique** [comment]
@evdokim as @rtobes said all these features should be under a section like 'Future work' or something like thtat

**Comment by rtobes** [comment]
That work is in progress and I hope that it will be ready to use very soon
