### ISSUE TITLE
MG7 and Metapasta

### ISSUE THREAD

**Issue by evdokim** [ohnosequences/IWBBIO-2014#6]
What we actually are going to present at IWBBIO? Metapasta or MG7?

**Comment by evdokim** [comment]
I would like to discuss it, because I would like to start preparing slides

**Comment by eparejatobes** [comment]
metapasta; it's only about naming I don't know exactly what are we doing with this. @rtobes ?

**Comment by rtobes** [comment]
Please include here the link to the abstract (or the abstract) that we finally sent.

**Comment by evdokim** [comment]
https://github.com/ohnosequences/IWBBIO-2014/blob/master/mg7/abstract.pdf?raw=true

**Comment by rtobes** [comment]
In my opinion we have to present MG7 because the abstract is about MG7 with the use of NISPERO for the BLAST part but after that @evdokim can present metapasta as a new fast way to do screening of samples to detect contamination or basic taxonomic assignments that allow to use LAST for alignment improving the execution time.
In summary Metapasta as a very quick assignment tool for screening of samples.

**Comment by evdokim** [comment]
but MG7 doesn't use nispero, isn't it?

**Comment by rtobes** [comment]
Sorry, you are rigth we are doing in the last projects the BLAST part with metapasta. I have corrected the previous message. 

But in the sent abstract is mentioned NISPERO. Does Metapasta  based on NISPERO?

**Comment by evdokim** [comment]
yes, metapasta based on some advanced version of nispero

**Comment by eparejatobes** [comment]
The abstract was written for the planned state of metapasta as of the conference date.

Some of these features are not implemented at this stage.

About the name, we kept MG7 as some sort of umbrella for metagenomics analysis

**Comment by rtobes** [comment]
OK

**Comment by evdokim** [comment]
let's discuss it. I want to clarify following:
- if I will present metapasta, how should I name it?
- should it refer to original MG7?
- what I should do be unimplemented features?

**Comment by evdokim** [comment]
@eparejatobes @rtobes 
can you take a look on my slides? also can we add to this repository @marina-manrique?

**Comment by evdokim** [comment]
https://github.com/ohnosequences/IWBBIO-2014/blob/master/mg7/presentation/presentation.pdf

**Comment by laughedelic** [comment]
BTW, @pablopareja doesn't have access to this repo tampoco

**Comment by marina-manrique** [comment]
@laughedelic I think this repo is public

**Comment by laughedelic** [comment]
Ok, anyway Pablo answered me by email already

**Comment by eparejatobes** [comment]
@evdokim @laughedelic I'll read it today
