### ISSUE TITLE
poster deadlines

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/IWBBIO-2014#7]
@evdokim @laughedelic 

Your poster session is **next Monday**; printing them takes some time (1-2 days, no weekends) and we (@rtobes and me) need to review them before. So:
- **Posters** should be finished before Wednesday **2014-04-02** **19:00**

**Comment by evdokim** [comment]
did it https://github.com/ohnosequences/IWBBIO-2014/tree/master/nispero

**Comment by eparejatobes** [comment]
@laughedelic @evdokim We will print them tomorrow morning as soon as any corrections/modifications are performed, so be here at the office **early** tomorrow morning!

**Comment by evdokim** [comment]
is 9 early enough?

**Comment by eparejatobes** [comment]
OK

**Comment by laughedelic** [comment]
Mine is in #4
