### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/IWBBIO-2014#8]
Hey @ohnosequences/members!

I have a general question: how do we license our documentation and materials like in this repo (slides/posters/talk notes/etc.)? 

I personally, don't know anything about licences for documentation. I've only heard about
- [GNU Free Documentation License](http://en.wikipedia.org/wiki/GNU_Free_Documentation_License)
- [Creative Commons](http://creativecommons.org/licenses/)

**Comment by eparejatobes** [comment]
This was already decided a year ago if I remember well. I should write some docs about it.
- https://creativecommons.org/licenses/by-sa/4.0/

**Comment by laughedelic** [comment]
Ok, cool, I've just read about it and also thought about cc-by-sa. btw, idris-people also use it ")
