### ISSUE TITLE
submitting abstract to Saint Petersburg Summer School of Bioinformatics 

### ISSUE THREAD

**Issue by evdokim** [ohnosequences/IWBBIO-2014#9]
@eparejatobes @rtobes  @marina-manrique
We would like with @laughedelic to make presentations on Saint Petersburg Summer School of Bioinformatics. The deadline  for submission is the 1st of June. Can we present there same abstracts as we had for IWBBIO but translated in Russian?

**Comment by evdokim** [comment]
Actually I even not sure that I'm going because of organizing issues (it's exactly the dates when we should start our placement in St. Andrews), but I prefer to submit something and then reject it if in the end I will not able to go

**Comment by rtobes** [comment]
Yes, but please this is a good occasion to do the corrections that Marina and me did for the content of the IWWBIO poster. I trust that you will do that because I can not review russian texts :)

**Comment by evdokim** [comment]
Yes, I will update slides, sorry for delay with that.
Also I'm going to change it a bit regarding to new feature, that I'm going to finish soon (lca and reads tracking).

Actually for me abstract is much complex thing, so I was asking mg7 abstract. I would like it to change it a bit for example use only metapasta word, and remove bam format mention, and translate it to Russian.
